# Generated by Django 4.2.7 on 2023-11-06 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_supplier_link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='ссылка на поставщика'),
            preserve_default=False,
        ),
    ]
